# Site settings
title: Agonías
email: agoniasoficial@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Agonías - Siempre cumpliendo con nuestro beber - Sant Adrià de Besòs - Ruta del Quinto
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://agoniasoficial.github.io" # the base hostname & protocol for your site
twitter_username: AgoniasOficial
instagram_username: agonias_oficial
facebook_username: AgoniasOficial
#github_username:  AgoniasOficial
#google_play: 'GDGX'
#google_plus_com: '109485346959707049693'  # Community link
#google_plus_per: '+GDGManagua'  #Personal link
#facebook_app_id: 12345

google_analytics: UA-25919296-1

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Twitter
    link: https://twitter.com/AgoniasOficial
  option2:
    name: Instagram
    link: https://www.instagram.com/agonias_oficial/
  option3:
    name: Facebook
    link: https://www.facebook.com/AgoniasOficial/

disqus: false
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
